# Generated by Django 4.0.3 on 2022-05-20 00:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('e_mail', models.EmailField(max_length=254)),
                ('message_type', models.CharField(choices=[('Discussion', 'Discussion'), ('question', 'question'), ('counseling', 'counseling')], max_length=12)),
                ('message', models.CharField(max_length=5000)),
                ('answer', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to=None)),
                ('location', models.CharField(choices=[('archive', 'archive'), ('gallery', 'gallery')], max_length=10)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Latest_result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_team_name', models.CharField(max_length=255)),
                ('first_team_image', models.ImageField(upload_to=None)),
                ('first_team_goals', models.PositiveIntegerField()),
                ('second_team_name', models.CharField(max_length=255)),
                ('second_team_image', models.ImageField(upload_to=None)),
                ('second_team_goals', models.PositiveIntegerField()),
                ('second_team_stat', models.CharField(choices=[('win', 'win'), ('lose', 'lose'), ('draw', 'draw')], max_length=5)),
                ('address', models.CharField(max_length=200)),
                ('clock', models.CharField(max_length=5)),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('league_type', models.CharField(choices=[('laliga', 'laliga'), ('championship', 'championship'), ('bundesliga', 'bundesliga')], max_length=12)),
                ('first_team_stat', models.CharField(choices=[('win', 'win'), ('lose', 'lose'), ('draw', 'draw')], max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='League_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_url', models.URLField()),
                ('pos', models.PositiveIntegerField()),
                ('team', models.CharField(max_length=255)),
                ('P', models.PositiveIntegerField()),
                ('W', models.PositiveIntegerField()),
                ('D', models.PositiveIntegerField()),
                ('L', models.PositiveIntegerField()),
                ('F', models.PositiveIntegerField()),
                ('A', models.PositiveIntegerField()),
                ('GD', models.SmallIntegerField()),
                ('Pts', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['Pts'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to=None)),
                ('video_url', models.URLField(blank=True, null=True)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('explain', models.TextField()),
                ('type', models.CharField(choices=[('news', 'news'), ('fringes', 'fringes'), ('academy', 'academy')], max_length=10)),
                ('season', models.CharField(choices=[('last_season', 'last_season'), ('current_season', 'current_season')], max_length=20)),
                ('author', models.CharField(max_length=255)),
                ('author_detail', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Next_matches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_image', models.ImageField(blank=True, null=True, upload_to='uplods/')),
                ('first_team_name', models.CharField(max_length=100)),
                ('first_team_image', models.ImageField(upload_to='uplods/')),
                ('second_team_name', models.CharField(max_length=100)),
                ('second_team_image', models.ImageField(upload_to='uplods/')),
                ('address', models.CharField(max_length=255)),
                ('header', models.CharField(max_length=255)),
                ('history_of_teams', models.TextField()),
                ('explain_future_plan', models.TextField()),
                ('clock', models.CharField(max_length=5)),
                ('day', models.PositiveSmallIntegerField()),
                ('month', models.CharField(choices=[('January', 'January'), ('February', 'February'), ('March', 'March'), ('April', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('August', 'August'), ('September', 'September'), ('October', 'October'), ('November', 'November'), ('December', 'December')], max_length=20)),
                ('league_type', models.CharField(choices=[('laliga', 'laliga'), ('championship', 'championship'), ('bundesliga', 'bundesliga')], max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='uploads/')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'demo_m_call',
            },
        ),
        migrations.CreateModel(
            name='Pro_soccer_info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('explain', models.TextField()),
                ('images', models.ImageField(blank=True, null=True, upload_to='uplods/')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('last_price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=None)),
                ('tag', models.CharField(choices=[('club_kit', 'club_kit'), ('accessories', 'accessories'), ('bust', 'bust'), ('sport_set', 'sport_set'), ('dumbbells', 'dumbbells')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Sport_fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('describe', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('field', models.CharField(blank=True, choices=[('martial', 'martial'), ('Bodybuilding', 'Bodybuilding'), ('Group', 'Group'), ('water hall', 'water hall'), ('Wrestling hall', 'Wrestling hall'), ('Salon', 'Salon')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('post', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=None)),
                ('team', models.CharField(choices=[('men', 'men'), ('ladies', 'ladies'), ('academy', 'academy'), ('veterans', 'veterans')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Team_honors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_goals', models.PositiveIntegerField(blank=True, null=True)),
                ('earned_awards', models.PositiveIntegerField(blank=True, null=True)),
                ('active_teams', models.PositiveIntegerField(blank=True, null=True)),
                ('active_player', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('nation', models.ImageField(upload_to=None)),
                ('age', models.PositiveIntegerField()),
                ('left', models.ImageField(upload_to=None)),
                ('join', models.ImageField(upload_to=None)),
                ('fee', models.DecimalField(decimal_places=1, max_digits=2)),
            ],
        ),
        migrations.CreateModel(
            name='Users_count',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('video_url', models.URLField()),
                ('league_type', models.CharField(blank=True, choices=[('laliga', 'laliga'), ('championship', 'championship'), ('bundesliga', 'bundesliga')], max_length=12, null=True)),
                ('type', models.CharField(choices=[('history', 'history'), ('archive', 'archive'), ('video', 'video'), ('academy', 'academy'), ('among people', 'among people')], max_length=15)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(blank=True, choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL')], max_length=5, null=True)),
                ('count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sport_news.product')),
            ],
        ),
    ]
